services:
  postgres-db:
    image: postgres:15
    container_name: postgres-db
    restart: always
    environment:
      - POSTGRES_DB=smartSpring
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin_password
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app-backend:
    build: .
    container_name: smart-spring-app
    ports:
      - "9089:9089"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/smartSpring
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin_password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - GMAIL_USERNAME=oumaymabramid@gmail.com
      - GMAIL_APP_PASSWORD=votre_mot_de_passe_google
    depends_on:
      - postgres-db
    restart: on-failure

volumes:
  postgres-data: