services:
  # --- Base de Données ---
  postgres-db:
    image: postgres:15
    container_name: postgres-db
    restart: always
    environment:
      - POSTGRES_DB=smartSpring
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin_password
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - smart-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin"]
      interval: 10s
      timeout: 5s
      retries: 5

  # --- SonarQube ---
  sonarqube:
    image: sonarqube:10.3-community
    container_name: sonarqube
    ports:
      - "9000:9000"
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
      - SONAR_JDBC_URL=jdbc:postgresql://postgres-db:5432/sonarqube
      - SONAR_JDBC_USERNAME=admin
      - SONAR_JDBC_PASSWORD=admin_password
    volumes:
      - sonarqube-data:/opt/sonarqube/data
      - sonarqube-logs:/opt/sonarqube/logs
      - sonarqube-extensions:/opt/sonarqube/extensions
    networks:
      - smart-network
    depends_on:
      postgres-db:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9000/api/system/status || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  # --- Application Backend ---
  app-backend:
    build: .
    container_name: smart-spring-app
    ports:
      - "9089:9089"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/smartSpring
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin_password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - GMAIL_USERNAME=oumaymabramid@gmail.com
      - GMAIL_APP_PASSWORD=votre_mot_de_passe_google
    depends_on:
      postgres-db:
        condition: service_healthy
    restart: on-failure
    networks:
      - smart-network

  # --- Jenkins (Auto-Configuré) ---
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    privileged: true
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - ./jenkins-config:/var/jenkins_config
    environment:
      - CASC_JENKINS_CONFIG=/var/jenkins_config/jenkins.yaml
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false -Dorg.jenkinsci.plugins.durabletask.BourneShellScript.HEARTBEAT_CHECK_INTERVAL=300
    networks:
      - smart-network
    depends_on:
      sonarqube:
        condition: service_healthy
    restart: always

networks:
  smart-network:
    driver: bridge

volumes:
  postgres-data:
  jenkins-data:
  sonarqube-data:
  sonarqube-logs:
  sonarqube-extensions:
